# Generated by Django 2.0.4 on 2018-04-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
