# Generated by Django 2.0.4 on 2018-04-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20180412_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.FileField(upload_to=''),
        ),
    ]
