# Generated by Django 2.0.4 on 2018-04-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_books_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='link',
        ),
    ]
