# Generated by Django 2.0.4 on 2018-04-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_remove_books_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_detail',
            field=models.TextField(default='text'),
        ),
    ]
